version: '3.0'

services:
  hub:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: uv run uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000 --reload --log-config ../logging.yaml 
    volumes:
      - ./app:/opt/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: unless-stopped
